<a href="https://colab.research.google.com/github/diaJalaeyRakhna/Assign7/blob/master/PIAIC52062_Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
import numpy as np
arr1 = np.arange(10)        # 1D array with elements 0-9
arr1 = arr1.reshape(2, 5)   # convert to 2D array
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
# use arr1 from Question1
arr2 = np.ones((2, 5), dtype=int)
np.vstack((arr1, arr2))     # vertically stack both arrays

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [33]:
# use arr1 and arr2 from prev. question
np.hstack((arr1, arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr3 = np.array([[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]])   # array of 5 arrays with 2 elements each
arr3.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [47]:
arr4 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8 , 9], [10, 11, 12, 13, 14]])    # dimension or shape = (3, 5)
np.reshape(arr4, -1)
# or simply
arr5 = arr4.reshape(-1)     # arr5 is 1D
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [ ]:
arr5.reshape

## Question:7

### Create 5x5 an array and find the square of an array?

## Question:8

### Create 5x6 an array and find the mean?

## Question:9

### Find the standard deviation of the previous array in Q8?

## Question:10

### Find the median of the previous array in Q8?

## Question:11

### Find the transpose of the previous array in Q8?

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

## Question:13

### Find the determinant of the previous array in Q12?

## Question:14

### Find the 5th and 95th percentile of an array?

## Question:15

### How to find if a given array has any null values?