<a href="https://colab.research.google.com/github/diaJalaeyRakhna/Assign7/blob/master/PIAIC52062_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
print("Null vector = ", np.zeros(10))

Null vector =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [ ]:
vector = np.arange(10, 50)
print("Array: ", vector)

Array:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [ ]:
print("Array's shape: ", vector.shape)

Array's shape:  (40,)


5. Print the type of the previous array in question 3

In [ ]:
print("Array's type: ", vector.dtype)

Array's type:  int64


6. Print the numpy version and the configuration


In [ ]:
print("NumPy version: ", np.__version__, "\nNumPy configuration: ", np.__config__)

NumPy version:  1.19.4 
NumPy configuration:  <module 'numpy.__config__' from '/usr/local/lib/python3.6/dist-packages/numpy/__config__.py'>


7. Print the dimension of the array in question 3


In [ ]:
print("Array's dimension: ", vector.ndim)

Array's dimension:  1


8. Create a boolean array with all the True values

In [ ]:
  print("Boolean array: ", np.ones(5, bool))

Boolean array:  [ True  True  True  True  True]


9. Create a two dimensional array




In [ ]:
arr2d = np.arange(10).reshape(2,5)      # or np.zeros(10).reshape(2,5)
print("2D Array: \n", arr2d)

2D Array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


10. Create a three dimensional array



In [ ]:
arr3d = np.arange(24).reshape(3,2,4)
print("3D Array: \n", arr3d)

3D Array: 
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [ ]:
print("Original vector: \n", vector)
print("\nReversed vector: \n", vector[::-1])

Original vector: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Reversed vector: 
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [ ]:
nullVec = np.zeros(10, int)
nullVec[4] = 1
print("(Almost) Null vector: ", nullVec)

(Almost) Null vector:  [0 0 0 0 1 0 0 0 0 0]


13. Create a 3x3 identity matrix

In [ ]:
print("Identity matrix: \n", np.identity(3, int))

Identity matrix: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [2]:
arr = np.array([1, 2, 3, 4, 5])
arr.

array([1, 2, 3, 4, 5])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

17. Extract all odd numbers from arr with values(0-9)

18. Replace all odd numbers to -1 from previous array

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

20. Create a 2d array with 1 on the border and 0 inside

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

26. Create a 10x10 array with random values and find the minimum and maximum values

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


40. Generate a matrix of 20 random values and find its cumulative sum